services:
  db:
    image: postgis/postgis:latest   # ✅ PG 16 + PostGIS 3.4 (стабильно)
    container_name: tinder-db
    environment:
      POSTGRES_DB: tinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tinder"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: tinder-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
