
### POST phone number request
POST http://localhost:8080/api/profile/verify-code
Content-Type: application/json

{
  "phoneNumber": "+37256349432"
}


### POST phone number request
POST http://localhost:8080/api/profile/phone
Content-Type: application/json

{
  "phoneNumber": "+37256349432"
}

### PATCH birthdate update
PATCH http://localhost:8080/api/profile/2/birthdate
Content-Type: application/json

{
  "birthdate": "1995-12-25"
}

### PATCH name update
PATCH http://localhost:8080/api/profile/2/name
Content-Type: application/json

{
  "name": "oleh"
}

### PATCH gender update
PATCH http://localhost:8080/api/profile/2/gender
Content-Type: application/json

{
  "gender": "MAN"
}

### POST upload photo
POST http://localhost:8080/api/photos/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="caption.jpg"
Content-Type: image/jpeg

< ./src/main/resources/photos/caption.jpg
--WebAppBoundary--

### GET requests
GET http://localhost:8080/api/profile/9


### UPDATE requests
PUT http://localhost:8080/api/profile/8
Content-Type: application/json

{
  "name": "dfsg",
  "age": 19,
  "bio": "Loafdafves hiking"
}



### DELETE requests
DELETE http://localhost:8080/api/profile/8

### GET profile welcome
GET http://localhost:8080/api/profile/1





